Repository EliaBergamin/Progetto-TecWeb, pull requests merged in 2024-11, with the labels that each got.

#6 Aggiunta documentazione
  docs/SEO/.gitkeep
  docs/assets/5e250d03-b345-8112-8005-2d9d834ad93a.svg
  docs/assets/8e1b913e-9626-80f5-8005-2ef72b4775a2.svg
  docs/assets/8e1b913e-9626-80f5-8005-2efcf0013742.svg
  docs/conventions/folder_structure.md
  docs/database/tables.md
  docs/index.md
  docs/procedures/index.md
  docs/website/structure.md
Labels: documentation

#11 Prima versione di pagina dettagio carta
  .gitignore
  public/html/dettaglio_carta.html
  public/images/.gitignore
  public/images/goku-super-saiyan.jpg
Labels: enhancement

#13 Feature/html homepage
  public/images/logoMuseo.png
  public/images/museumIcon.png
  public/index.html
Labels: help wanted

#22 Feature/html dettagliosala
  public/html/dettaglio_carta.html
  public/html/dettaglio_sala.html
  public/html/prenotazione.html
  public/html/registrazione.html
  public/index.html
Labels: help wanted

#26 Feature/html recensioni
  public/css/.gitignore
  public/css/style.css
  public/html/recensioni.html
  public/html/recensisci.html
Labels: enhancement

#28 Aggiornato dockerfile con mount del file init.sql e permessi aggiornati
  README.md
  docker-compose.yml
  docs/database/init.sql
Labels: enhancement

#43 Feature/css index.html
  public/css/style.css
  public/images/immcarosello1.jpg
  public/images/immcarosello2.jpg
  public/images/immcarosello3.jpg
  public/index.html
  public/js/dynamic.js
Labels: enhancement

#49 Feature/css dettaglio sala
  public/css/style.css
  public/html/dettaglio_sala.html
  public/images/provaSala.jpg
Labels: enhancement, help wanted

#41 Primo stile per pagina dettaglio opera
  public/css/style.css
  public/html/dettaglio_carta.html
Labels: enhancement

#51 Stile pagina virtual tour
  public/css/style.css
  public/html/virtual_tour.html
  public/images/sala-dragon-ball.png
  public/images/sala-gormiti.jpeg
  public/images/sala-pokemon.jpg
  public/images/sala-yu-gi-oh.jpeg
  public/js/.gitignore
Labels: enhancement

#39 Feature/schema db
  docs/database/schema.drawio
Labels: documentation
